### ISSUE TITLE
Live lock in FlippableDataContainer.put()

### ISSUE THREAD

**Issue by ValleZ** [RovoMe/JDrum#2]
I've tried to call drum.checkUpdate() about a million times and FlippableDataContainer falls into live lock in put method. Making all methods synchronized fixes the issue.

ps It happens more often w/o debugger attached and maybe related to throughput. When you move 
"this.berkeleyDB.sync();" out of loop in compareDataWithDataStore() performance goes from ~100 checks per second to ~35000 checks per second what probably helps to reproduce the issue.

**Comment by RovoMe** [comment]
May I ask how many threads you had active? By design, `FlippableDataContainer` is designed as lock-free implementation which makes use of `AtomicReference` internally. The only thing that logically may occur is that if multiple threads fight over the `FlippableData` object currently stored in the `AtomicReference`, only one thread actually can write into the reference (via [`compareAndSet(...)`](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicReference.html#compareAndSet-V-V-)) as the previous item of the `AtomicReference` is the same as the retrieved one and only then the comparison should succeed and the new object get stored into the reference. All the other threads should fail the comparison, as they have now an outdated version of that object, and hence enter the next iteration of the endless loop and re-attain a reference to the currently stored object. I have to look more thoroughly into how multiple threads interact with the `FlippableDataContainer` and if there is a chance for a thread to end up in an endless loop.

`synchronized` prevents multiple threads from entering the same code block which solves cuncurrency issues for sure (if done right) but may also lead to thread context switches which further are quite costly in high-performance, multi-threaded environments. With lock-free implementations all threads remain active and thus avoid a context switch though also increase the overall CPU utilization notably. DRUM tries by design to avoid synchronization calls if possible to prevent thread context-switches and thus increase overall throughput.

I guess you are right with the move of the BerkeleyDB synchronization out of the loop. May I also ask if you use JDrum inside a test scenario currently or if you are using it on (more or less) live-data? I am aware that the current tests are very limited and need to be updated, especially with large-scale input (even if it is randomly generated)

**Comment by ValleZ** [comment]
1 writer thread. I don't use it since it doesn't give any benefits over standalone DB.

**Comment by ValleZ** [comment]
test was:
`package at.rovo;

import at.rovo.caching.drum.*;
import at.rovo.caching.drum.event.DrumEvent;
import at.rovo.caching.drum.internal.Drum;
import at.rovo.caching.drum.internal.backend.berkeley.BerkeleyDBStoreMergerFactory;

import java.util.Random;

public class Test implements DrumListener, Dispatcher<String, String> {
    private final Drum<String, String> drum;
    private final long start;
    private final Object statLock = new Object();

    public Test() throws Exception {
        int bufSize = 1 << 10;
        System.out.println("buf " + bufSize);
        drum = new DrumBuilder<>("keyValueName", String.class, String.class)
                .numBucket(8).bufferSize(bufSize)
                .dispatcher(this)
                .listener(this)
                .factory(BerkeleyDBStoreMergerFactory.class)
//                .factory(DataStoreMergerFactory.class)
                .build();
        start = System.currentTimeMillis();
    }

    public static void main(String[] args) throws Exception {
        try {
            Test main = new Test();
            new Thread(() -> {
                while (main.isRunning()) {
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                        break;
                    }
                    main.logStat();
                }
                System.out.println("FINISHED!");
                try {
                    main.dispose();
                } catch (DrumException e) {
                    e.printStackTrace();
                }
            }).start();
            main.run();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void logStat() {
        long time = System.currentTimeMillis() - start;
        System.out.println(" updates " + updates + " answers " + answers + ", " + time / 1000 + " s, answers/s avg " + (1000L * answers / time));
    }

    private boolean isRunning() {
        return updates < N || answers < N;
    }

    private final Random random = new Random();

    private volatile int updates;
    private volatile int answers;
    private static final int N = 200000;

    private void run() {
        try {
            int chunkSize = 10000;
            for (int i = 0; i < N / chunkSize; i++) {
                for (int j = 0; j < chunkSize; j++) {
                    long val = random.nextLong();
                    drum.checkUpdate(val, null, "" + val);
                    updates++;
                }
//                synchronized (statLock) {
//                    while (answers < updates) {
//                        statLock.wait(1000);
//                    }
//                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("update finished");
    }

    private void dispose() throws DrumException {
        drum.dispose();
    }

    @Override
    public void update(DrumEvent<? extends DrumEvent<?>> event) {
    }

    @Override
    public void uniqueKeyCheck(Long key, String aux) {
        if (Long.parseLong(aux) != key) {
            System.out.println("False unique " + key + " " + aux);
        }
    }

    @Override
    public void duplicateKeyCheck(Long key, String value, String aux) {
        System.out.println("dup check " + key + " " + aux);

    }

    @Override
    public void uniqueKeyUpdate(Long key, String value, String aux) {
        synchronized (statLock) {
            answers++;
            statLock.notifyAll();
        }
    }

    @Override
    public void duplicateKeyUpdate(Long key, String value, String aux) {
        System.out.println("dup update " + key + " " + aux);
        synchronized (statLock) {
            answers++;
            statLock.notifyAll();
        }
    }

    @Override
    public void update(Long key, String value, String aux) {
    }
}
`

**Comment by RovoMe** [comment]
@ValleZ I found time to work on the issue and was able to fix the issue in `FlippableDataContainer::put`. Sorry for the long delay, though I had not much time since x-mas. Nevertheless, hope the fix is still useful to you.
